last changes
git-svn-id: file:///home/johnw/src/.svk/local/local/attic/trunk@942 9cb8bb9c-67ef-4b35-ac45-fd8f6883d615

diff --git a/acprep b/acprep
--- a/acprep
+++ b/acprep
@@ -17,9 +17,18 @@ else
 fi
 autoconf
 
-INCDIRS="-I/sw/include -I/usr/local/include"
-LIBDIRS="-L/sw/lib -L/usr/local/lib"
-SWITCHES="--disable-shared"
+INCDIRS="-I/usr/local/include"
+INCDIRS="$INCDIRS -I/sw/include"
+INCDIRS="$INCDIRS -I/usr/X11R6/include"
+INCDIRS="$INCDIRS -I/usr/include/httpd/xml"
+#INCDIRS="$INCDIRS -I/sw/include/libofx"
+INCDIRS="$INCDIRS -I/usr/include/python2.3"
+INCDIRS="$INCDIRS -I/sw/include/boost"
+
+LIBDIRS="-L/usr/local/lib"
+LIBDIRS="$LIBDIRS -L/sw/lib"
+LIBDIRS="$LIBDIRS -L/usr/X11R6/lib"
+LIBDIRS="$LIBDIRS -L/usr/lib/python2.3/config"
 
 SYSTEM=`uname -s`
 if [ $SYSTEM = Linux ]; then
@@ -32,12 +41,52 @@ else
     CXXFLAGS=""
 fi
 
+# Building the command-line tool as a shared library is a luxury,
+# since there are no clients except a GUI tool which might use it (and
+# that is built again anyway by Xcode).
+SWITCHES="--disable-shared"
+
+HERE="$PWD"
+
+if [ -d "$HOME/Products" ]; then
+    projdir="$HOME/Products/$(basename $HERE)"
+    if [ ! -d "$projdir" ]; then
+	mkdir -p "$projdir"
+    fi
+    cd "$projdir" || (echo "Cannot change to $projdir"; exit 1)
+fi
+
 if [ "$1" = "--debug" ]; then
     shift 1
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
-	CXXFLAGS="$CXXFLAGS -g" $SWITCHES --enable-debug
-else
-    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" $SWITCHES
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" $SWITCHES \
+	--enable-debug "$@"
+elif [ "$1" = "--python-debug" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" $SWITCHES \
+	--enable-debug --enable-python "$@"
+elif [ "$1" = "--opt" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC" "$@" $SWITCHES
+elif [ "$1" = "--flat-opt" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450" "$@" $SWITCHES
+elif [ "$1" = "--safe-opt" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
+	CXXFLAGS="-fomit-frame-pointer -O3 -mcpu=7450 -fPIC -DDEBUG_LEVEL=1" "$@" \
+	$SWITCHES
+elif [ "$1" = "--perf" ]; then
+    shift 1
+    "$HERE/configure" --srcdir="$HERE" \
+	CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg" "$@" \
+	$SWITCHES
 fi
 
 rm AUTHORS COPYING
